# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



flutter_application_path = 'my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')



target 'KLNativeAddFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  install_all_flutter_pods(flutter_application_path)

  
  
  use_frameworks!

  # Pods for KLNativeAddFlutter

end
